[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
tokio = { version = "1", features = ["full"] }
actix-rt = "2"
reqwest = { version = "0.11", features = ["full"] }

[lib]
path = "src/lib.rs"
