#! configuration/local.yaml
application:
  host: 127.0.0.1
  port: 8000
  base_url: "http://127.0.0.1"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "postgres"
  database_name: "newsletter"
  require_ssl: false
